services:
  - type: web
    name: exontix-bot-api
    env: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
